
import React, { useState, useEffect, useRef } from 'react';
import type { HairstylistReport } from '../types';
import { Icon } from './Icon';
import { TurnaroundView } from './TurnaroundView';
import { generateHairstylistPdf } from '../utils/pdfGenerator';

interface HairstylistReportDisplayProps {
  reportData: { report: HairstylistReport; simulatedImage: any };
  clientImage: string;
  referenceImage: string;
  onReset: () => void;
  setIsLoading: (isLoading: boolean) => void;
  setLoadingMessage: (message: string) => void;
  setShareMessage: (message: string | null) => void;
}

const VerdictCard: React.FC<{ verdict: string; justification: string }> = ({ verdict, justification }) => {
    const verdictColor = {
        'Altamente Recomendado': 'border-emerald-500 bg-emerald-900/30',
        'Recomendado com Adaptações': 'border-amber-500 bg-amber-900/30',
        'Não Recomendado': 'border-red-500 bg-red-900/30',
    }[verdict] || 'border-gray-600';

    const verdictTextColor = {
        'Altamente Recomendado': 'text-emerald-300',
        'Recomendado com Adaptações': 'text-amber-300',
        'Não Recomendado': 'text-red-300',
    }[verdict] || 'text-gray-300';

    return (
        <div className={`p-4 rounded-xl border ${verdictColor}`}>
            <h3 className={`text-xl font-bold ${verdictTextColor} mb-2`}>{verdict}</h3>
            <p className="text-gray-300 leading-relaxed">{justification}</p>
        </div>
    );
};

export const HairstylistReportDisplay: React.FC<HairstylistReportDisplayProps> = ({ reportData, clientImage, referenceImage, onReset, setIsLoading, setLoadingMessage, setShareMessage }) => {
  const { report, simulatedImage } = reportData;
  const [highlightedStep, setHighlightedStep] = useState<number | null>(null);
  const diagramsContainerRef = useRef<HTMLDivElement>(null);

  const handleShare = async () => {
    setIsLoading(true);
    setLoadingMessage('Gerando dossiê completo...');
    setShareMessage(null);
    try {
      const pdfBlob = await generateHairstylistPdf(reportData, clientImage, referenceImage);
      const pdfFile = new File([pdfBlob], 'dossie-hairstylist-visagista.pdf', { type: 'application/pdf' });
      
      if (navigator.share && navigator.canShare({ files: [pdfFile] })) {
        await navigator.share({
          title: 'Análise Hairstylist Visagista',
          text: `Confira o plano de corte para ${report.cuttingPlan.styleName}.`,
          files: [pdfFile],
        });
      } else {
        // Fallback to download
        const link = document.createElement('a');
        link.href = URL.createObjectURL(pdfBlob);
        link.download = `dossie-${report.cuttingPlan.styleName.replace(/\s+/g, '-').toLowerCase()}.pdf`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(link.href);
        setShareMessage("PDF baixado com sucesso!");
      }
    } catch (err) {
       console.error("PDF generation/sharing failed:", err);
       if ((err as Error).name !== 'AbortError') {
         setShareMessage('Ocorreu um erro ao gerar ou compartilhar o PDF.');
       }
    } finally {
      setIsLoading(false);
      setTimeout(() => setShareMessage(null), 4000);
    }
  };

  useEffect(() => {
    const container = diagramsContainerRef.current;
    if (!container) return;

    // Reset previous highlights
    container.querySelectorAll('.highlight').forEach(el => el.classList.remove('highlight'));

    if (highlightedStep !== null) {
        // Target specifically by ID as generated by AI (step-1, step-2...)
        // We look inside all SVG diagrams for matching IDs
        const targetElements = container.querySelectorAll(`[id='step-${highlightedStep}']`);
        targetElements.forEach(el => el.classList.add('highlight'));
    }
  }, [highlightedStep, report.cuttingPlan.diagrams]);

  // Inject styles for the highlight effect
  const svgStyles = `
    .highlight { 
        stroke: #00ffcc !important; 
        stroke-width: 3px !important; 
        filter: drop-shadow(0 0 5px #00ffcc); 
        opacity: 1 !important;
        transition: all 0.3s ease;
    }
    g[id^='step-'] { 
        transition: all 0.3s ease; 
        cursor: pointer;
    }
  `;

  return (
    <div className="bg-gray-800 rounded-2xl p-6 h-full flex flex-col">
      <style>{svgStyles}</style>
      <div className="flex-shrink-0 flex justify-between items-center pb-4 mb-4 border-b border-gray-700 gap-4">
        <h2 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-emerald-300 to-green-400">
          Análise Visagista Completa
        </h2>
        <div className="flex items-center gap-2">
          <button onClick={handleShare} className="flex items-center gap-2 px-4 py-2 bg-emerald-600 text-white rounded-lg font-semibold hover:bg-emerald-500 transition-colors text-sm">
            <Icon name="share" className="w-5 h-5" />
            Compartilhar / Salvar PDF
          </button>
          <button onClick={onReset} className="px-4 py-2 bg-gray-700 text-white rounded-lg font-semibold hover:bg-gray-600 transition-colors text-sm">
            Nova Análise
          </button>
        </div>
      </div>

      <div className="flex-grow overflow-y-auto pr-2 space-y-6">
        {/* Image Comparison - Turnaround View */}
        <div className="w-full">
            <TurnaroundView 
                frontImage={simulatedImage.front} 
                sideImage={simulatedImage.side} 
                backImage={simulatedImage.back} 
            />
        </div>

        {/* Report Details */}
        <div className="space-y-6">
            <VerdictCard verdict={report.viabilityVerdict} justification={report.viabilityJustification} />

            {report.adaptationRecommendations && report.adaptationRecommendations.length > 0 && (
                 <div className="bg-gray-900/50 p-4 rounded-xl">
                    <h3 className="text-xl font-semibold text-amber-300 mb-3">Recomendações de Adaptação</h3>
                    <ul className="list-disc list-inside space-y-2 text-gray-300">
                        {report.adaptationRecommendations.map((rec, i) => <li key={i}>{rec}</li>)}
                    </ul>
                </div>
            )}
            
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                 <div className="bg-gray-900/50 p-4 rounded-xl">
                    <h3 className="text-xl font-semibold text-emerald-300 mb-3">Plano de Corte ({report.cuttingPlan.styleName})</h3>
                    <ol className="list-decimal list-inside space-y-2 text-gray-300 mb-4">
                        {report.cuttingPlan.steps.map((step, i) => (
                            <li 
                                key={i}
                                onMouseEnter={() => setHighlightedStep(i + 1)}
                                onMouseLeave={() => setHighlightedStep(null)}
                                className={`p-2 rounded cursor-pointer transition-colors ${highlightedStep === i + 1 ? 'bg-emerald-900/50 text-white font-medium border-l-4 border-emerald-500' : 'hover:bg-gray-800'}`}
                            >
                                {step}
                            </li>
                        ))}
                    </ol>
                    <div ref={diagramsContainerRef} className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        {report.cuttingPlan.diagrams.map((diag, i) => (
                             <div key={i} className="bg-gray-900 border border-gray-700 p-4 rounded-lg flex flex-col items-center">
                                 <h4 className="font-semibold text-center text-sm mb-2 text-emerald-300">{diag.title}</h4>
                                 <div className="w-full h-full" dangerouslySetInnerHTML={{ __html: diag.svg }} />
                             </div>
                        ))}
                    </div>
                 </div>

                 <div className="bg-gray-900/50 p-4 rounded-xl">
                    <h3 className="text-xl font-semibold text-emerald-300 mb-3">Home Care & Estilização ({report.homeCare.brand})</h3>
                    <div className="space-y-4">
                        <div>
                            <h4 className="text-lg font-semibold text-white mb-2">Produtos Recomendados</h4>
                            <div className="space-y-3">
                                {report.homeCare.products.map((prod, i) => (
                                    <div key={i} className="bg-gray-700/50 p-3 rounded-md">
                                        <p className="font-semibold">{prod.name}</p>
                                        <p className="text-sm text-gray-400">{prod.purpose}</p>
                                    </div>
                                ))}
                            </div>
                        </div>
                         <div>
                            <h4 className="text-lg font-semibold text-white mb-2">Guia de Aplicação</h4>
                            <ol className="list-decimal list-inside space-y-2 text-gray-300">
                                {report.homeCare.applicationGuide.map((step, i) => <li key={i}>{step}</li>)}
                            </ol>
                        </div>
                    </div>
                 </div>
            </div>
        </div>

      </div>
    </div>
  );
};